version: '3.7'

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: always
    ports:
      - "55414:55414"
      - "55415:55415"
    environment:
      - PUID=1000 # Enter the UID of the user who should own the files here
      - PGID=1000  # Enter the GID of the user who should own the files here
      - TZ=Europe/Madrid # Enter your timezone
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/urbackup
      - /home/umbrel/umbrel/external/Elements/UrBackup/backups:/backups
      # - /home/umbrel/umbrel/network/ds213-nas.local/UrBackup/backups:/backups
      # Uncomment the next line if you want to bind-mount the www-folder
      #- /path/to/wwwfolder:/usr/share/urbackup
    network_mode: "host"
    # Uncomment the following two lines if you're using BTRFS support
    #cap_add:
    #  - SYS_ADMIN
    # Uncomment the following two lines if you're using ZFS support
    #devices:
    #  - /dev/zfs:/dev/zfs
